








analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  errors:
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  
  
  
  
  
  
  
  
  
  
  rules:
    use_build_context_synchronously: true
    strict_top_level_inference: false
    
    



